In [1]:
import tensorflow as tf
import numpy as np

def get_train_data():
    '''
    X_train.shape: (N, 2)
    y_train.shape: (N,)
    '''
    X_train = np.array([[1, 1], [1, 2]])
    y_train = np.array([1, 2])
    return X_train, y_train

def model(X):
    '''
    W.shape: (2, 1)
    b.shape: (1,)
    y.shape: (N, 1)
    return : (N,)
    '''
    W = tf.get_variable("W", shape=[2, 1])
    b = tf.get_variable("b", shape=[1])
    y = tf.matmul(X, W) + b
    return y[:, 0]

def run(variables, feed_dict, epoches):
    '''
    print loss, prediction, weights every 10 iterations
    '''
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        # for o in sess.graph.get_operations():
        #     print(o.name)
        # for v in tf.global_variables():
        #     print(v.name)
        W = sess.graph.get_tensor_by_name("W:0")
        b = sess.graph.get_tensor_by_name("b:0")
        for e in range(epoches):
            pred_val, loss_val, _ = sess.run(variables, feed_dict = feed_dict)
            if e % 10 == 0:
                print("Epoch {0}, loss = {1:.3g}, ".format(e + 1, loss_val))
                print("prediction:", pred_val)
                print("W:\n", W.eval())
                print("b:\n", b.eval())

def main():
    # placeholders
    X = tf.placeholder(tf.float32, [None, 2])
    y = tf.placeholder(tf.float32, [None])
    # graph
    pred = model(X)
    # loss
    loss = tf.sqrt(tf.losses.mean_squared_error(pred, y))
    # optimizer
    optimizer = tf.train.AdamOptimizer(0.1)
    training  = optimizer.minimize(loss)
    # training data
    X_train, y_train = get_train_data()
    print("X_train.shape:", X_train.shape, "y_train.shape:", y_train.shape)
    # run tensorflow
    variables = [pred, loss, training]
    feed_dict = {X: X_train, y: y_train}
    epoches = 100
    run(variables, feed_dict, epoches)

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
main()

X_train.shape: (2, 2) y_train.shape: (2,)
Epoch 1, loss = 2.41, 
prediction: [-0.76324785 -0.9232073 ]
W:
 [[-0.5982354 ]
 [-0.05995946]]
b:
 [0.19494694]
Epoch 11, loss = 0.68, 
prediction: [1.803855  2.5265996]
W:
 [[0.14665805]
 [0.74042   ]]
b:
 [0.93984056]
Epoch 21, loss = 0.382, 
prediction: [0.9294844 1.4637583]
W:
 [[-0.2116692 ]
 [ 0.54222536]]
b:
 [0.5815133]
Epoch 31, loss = 0.211, 
prediction: [1.2851529 2.0855114]
W:
 [[-0.18414046]
 [ 0.7944773 ]]
b:
 [0.609042]
Epoch 41, loss = 0.107, 
prediction: [1.1367028 2.0649672]
W:
 [[-0.31308296]
 [ 0.9345046 ]]
b:
 [0.48009944]
Epoch 51, loss = 0.0509, 
prediction: [0.9416442 1.9579452]
W:
 [[-0.43152705]
 [ 1.0297371 ]]
b:
 [0.36165538]
Epoch 61, loss = 0.0194, 
prediction: [0.9958418 2.027056 ]
W:
 [[-0.4264076]
 [ 1.0087409]]
b:
 [0.36677483]
Epoch 71, loss = 0.048, 
prediction: [1.0483956 2.0476186]
W:
 [[-0.36988577]
 [ 1.0010339 ]]
b:
 [0.42329666]
Epoch 81, loss = 0.0579, 
prediction: [0.9502841 1.9349977]
W:
 [[-0.40614